# configuration file for bulk-RNAseq snake pipeline


# folder of reads
readDataDir: "ngs-test-data/reads/"
# where should the results go?
outputDir: "results/"

# which reference to use
ref:
  # the STAR index
  sequence: "ngs-test-data/ref/genome.chr21.fa"
  # gtf file with transcripts
  annotation: "ngs-test-data/ref/annotation.chr21.gtf"
  # specifies the length of the genomic sequence around the annotated junction
  # to be used in constructing the splice junctions database. Ideally, this length should be equal
  # to the ReadLength-1, where ReadLength is the length of the reads. For instance, for Illumina
  # 2x100b paired-end reads, the ideal value is 100-1=99. In case of reads of varying length, the
  # ideal value is max(ReadLength)-1. In most cases, a generic value of 100 will work as
  # well as the ideal value.
  star_overhang: 99


# overview PCA 
pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

# define (multiple) contrasts between samples for DESeq2 differential expression detection
diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    treated_vs_untreated: # name of contrast, with list of sample annotations to compare
      - treated
      - untreated
params:
  trimmo_threads: "8"
  trimmo_adapter_path: "ngs-test-data/adapters/TruSeq3-PE-2.fa"
  star: "" # mapping parameters for star
  #star indexing: since we are only one chromosome, the genomeSAindexNbases should be smaller than default 11
  star_index: "--limitGenomeGenerateRAM 322122547200   --limitSjdbInsertNsj 30000000 --genomeSAindexNbases 11"
